# Tutorial: House Price

In this tutorial, you will be using a dataset consists of houses and its price and try to develop a model to estimate the price of a house if given its characteristics

## Importing the libraries

In [ ]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import scale 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV
from sklearn.metrics import mean_squared_error

## Importing the dataset

In [ ]:
#import dataset (Housing-simple.csv)

In [ ]:
#Check the data

,price(100k),area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,133.00,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,122.50,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,122.50,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,122.15,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,114.10,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [ ]:
#check for general property of data (data type/ null entries)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price(100k)       545 non-null    float64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: float64(1), int64(5), object(7)
memory usage: 55.5+ KB

,price(100k),area,bedrooms,bathrooms,stories,parking
count,545.000000,545.000000,545.000000,545.000000,545.000000,545.000000
mean,47.667292,5150.541284,2.965138,1.286239,1.805505,0.693578
std,18.704396,2170.141023,0.738064,0.502470,0.867492,0.861586
min,17.500000,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,34.300000,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,43.400000,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,57.400000,6360.000000,3.000000,2.000000,2.000000,1.000000
max,133.000000,16200.000000,6.000000,4.000000,4.000000,3.000000

## Data Preprocessing

In [ ]:
df.columns

Index(['price(100k)', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
#list of columns that are yes/no

In [ ]:
#check unique values just to be sure
for c in binary_column:
    #print unique value of each column here

In [ ]:
#replacing yes with 1 and no with 0
for c in binary_column:
    #replacing value of yes/no of the columns here

In [ ]:
#check the number of each category of "furnishing status"

In [ ]:
#convert "furnishingstatus" into one-hot encoding (dummy variable)

In [ ]:
df.head()

In [ ]:
#looking at distribution of area

In [ ]:
#looking at distribution of bedrooms

# Correlation Matrix

In [ ]:
#Compute correlation matrix here

In [ ]:
# Hint: use sns.heatmap()

**plot ปัจจัยที่มีผลต่อ price ที่สุด จาก  correlation matrix**

In [ ]:
# plt.scatter(df["area"],df["price(100k)"])
sns.lmplot(x="area",y="price(100k)", data=df)

## Splitting the dataset into the Training set and Test set

In [ ]:
y = 
X =

In [ ]:
# Split data into training and test sets (30% test set)
X_train, X_test , y_train, y_test =

## Scaling features

In [ ]:
X_train.head()

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
#scaling the desired columns (it's ok for 1/0 because it's min/max scaling)
X_train.loc[:,:]= scaler.fit_transform(X_train.loc[:,:])

In [ ]:
X_train.head()

## Training the MLR, Ridge, Lasso model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

# Multiple Regression Model
MLR = LinearRegression()
MLR.fit(X_train, y_train)

# Ridge Regression Model
ridge = Ridge()
ridge.fit(X_train, y_train)

# Lasso Regression Model
lasso = Lasso()
lasso.fit(X_train,y_train);

## Model Results

In [ ]:
#Transform X_test with the same transformation as X_train

In [ ]:
#Note that score() gives us r2 score
print("MLR Training Set Score:{:.2f}".format(MLR.score(X_train, y_train)))
print("MLR Test Set Score:{:.2f}".format(MLR.score(X_test, y_test)))

In [ ]:
#Ridge performs a little bit worse for training, but generalize a little better
print("Ridge Training Set Score:{:.2f}".format(ridge.score(X_train, y_train)))
print("Ridge Test Set Score:{:.2f}".format(ridge.score(X_test, y_test)))

print("Total number of features:{}".format(X_train.shape[1]))
print("Number of features used for Ridge:{}".format(np.sum(ridge.coef_ !=0)))

In [ ]:
#Lasso performs worse for training, but doesn't affect the test accuracy much 
print("Lasso Training Set Score:{:.2f}".format(lasso.score(X_train, y_train)))
print("Lasso Test Set Score:{:.2f}".format(lasso.score(X_test, y_test)))

#Note that out of 18 features, Lasso deemed almost all of them of them less relevant and forced them to 0
print("Total number of features:{}".format(X_train.shape[1]))
print("Number of features used for Lasso:{}".format(np.sum(lasso.coef_ !=0)))

Why does Lasso provide relatively poor performance compared to MLR and Ridge?

## Regularization

Now we're studying the impact of regularization parameters (in sklearn it's called "alpha", not "lambda" like in the slides)

In [ ]:
#Notice the regularization effects
ridge100 = Ridge(alpha=100).fit(X_train, y_train)
print("Ridge100 Training Set Score:{:.2f}".format(ridge100.score(X_train, y_train)))
print("Ridge100 Test Set Score:{:.2f}".format(ridge100.score(X_test, y_test)))
print()

ridge10 = Ridge(alpha=10).fit(X_train, y_train)
print("Ridge10 Training Set Score:{:.2f}".format(ridge10.score(X_train, y_train)))
print("Ridge10 Test Set Score:{:.2f}".format(ridge10.score(X_test, y_test)))
print()

ridge1 = Ridge(alpha=1).fit(X_train, y_train)
print("Ridge1 Training Set Score:{:.2f}".format(ridge1.score(X_train, y_train)))
print("Ridge1 Test Set Score:{:.2f}".format(ridge1.score(X_test, y_test)))
print()

ridge01 = Ridge(alpha=0.1).fit(X_train, y_train)
print("Ridge01 Training Set Score:{:.2f}".format(ridge01.score(X_train, y_train)))
print("Ridge01 Test Set Score:{:.2f}".format(ridge01.score(X_test, y_test)))
print()

ridge00001 = Ridge(alpha=0.0001).fit(X_train, y_train)
print("Ridge00001 Training Set Score:{:.2f}".format(ridge00001.score(X_train, y_train)))
print("Ridge00001 Test Set Score:{:.2f}".format(ridge00001.score(X_test, y_test)))

In [ ]:
#Lasso
lasso1 = Lasso(alpha=1).fit(X_train,y_train);
print("lasso1 Training Set Score:{:.2f}".format(lasso1.score(X_train, y_train)))
print("lasso1 Test Set Score:{:.2f}".format(lasso1.score(X_test, y_test)))
print("Number of features used in lasso1:{}".format(np.sum(lasso1.coef_ !=0)))
print()

lasso01 = Lasso(alpha=0.1).fit(X_train,y_train)
print("lasso01 Training Set Score:{:.2f}".format(lasso01.score(X_train, y_train)))
print("lasso01 Test Set Score:{:.2f}".format(lasso01.score(X_test, y_test)))
print("Number of features used in lasso01:{}".format(np.sum(lasso01.coef_ !=0)))
print()

lasso001 = Lasso(alpha=0.01).fit(X_train,y_train)
print("lasso001 Training Set Score:{:.2f}".format(lasso001.score(X_train, y_train)))
print("lasso001 Test Set Score:{:.2f}".format(lasso001.score(X_test, y_test)))
print("Number of features used in lasso001:{}".format(np.sum(lasso001.coef_ !=0)))
print()

lasso00001 = Lasso(alpha=0.00001).fit(X_train,y_train)
print("lasso00001 Training Set Score:{:.2f}".format(lasso00001.score(X_train, y_train)))
print("lasso00001 Test Set Score:{:.2f}".format(lasso00001.score(X_test, y_test)))
print("Number of features used in lasso00001:{}".format(np.sum(lasso00001.coef_ !=0)))

## Inspecting coefficients

In [ ]:
#MLR
MLR_coeff_df = pd.DataFrame(MLR.coef_,X.columns,columns=['Coefficient'])
MLR_coeff_df

In [ ]:
#Ridge 
#Exercise: Try changing to observe coefficient of Ridge at different regularization value
Ridge_coeff_df = pd.DataFrame(ridge1.coef_,X.columns,columns=['Coefficient'])
Ridge_coeff_df

In [ ]:
#Lasso
#Exercise: Try changing to observe coefficient of Lasso at different regularization value
Lasso_coeff_df = pd.DataFrame(lasso01.coef_,X.columns,columns=['Coefficient'])
Lasso_coeff_df